#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generates Apps/DigitPad/FontAtlas.h: anti-aliased glyph strips for the DigitPad UI.

Glyphs are rendered from DejaVu Sans with ImageMagick, quantized to 16 coverage levels and
run-length encoded into printable strings, so the app needs no font library at run time.

    python3 Apps/DigitPad/Tools/make_font_atlas.py [fonts-dir]
"""
import os
import re
import subprocess
import sys

FONT_DIR = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu"
ASCII = "".join(chr(c) for c in range(32, 127))
FONTS = [  # (C name, file, point size, characters)
    ("font_ui", "DejaVuSans.ttf", 15, ASCII),
    ("font_title", "DejaVuSans-Bold.ttf", 21, ASCII),
    ("font_big", "DejaVuSans-Bold.ttf", 84, "0123456789?"),
]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "FontAtlas.h")


def im_text(ch):
    """Escape ImageMagick's annotate syntax (% escapes, leading @ file reads, backslash)."""
    return {"%": "%%", "\\": "\\\\", "@": "\\@"}.get(ch, ch)


def metrics(ttf, size, chars):
    args = ["convert", "-debug", "annotate", "xc:", "-font", ttf, "-pointsize", str(size)]
    for ch in chars:
        args += ["-annotate", "0", im_text(ch) if ch != " " else "x"]
    log = subprocess.run(args + ["null:"], capture_output=True, text=True).stderr
    num = r"(-?[\d.]+)"
    found = re.findall(rf"Metrics: text: .*?; width: {num}; height: {num}; ascent: {num}; descent: {num}", log)
    assert len(found) == len(chars), (len(found), len(chars))
    widths = [round(float(w)) for w, _, _, _ in found]
    if " " in chars:  # the space was measured as 'x'; use a narrower advance
        widths[chars.index(" ")] = max(3, size // 3)
    _, height, ascent, descent = (round(float(v)) for v in found[0])
    return widths, ascent, ascent - descent


def render(name, ttf, size, chars):
    advances, ascent, height = metrics(ttf, size, chars)
    pad = max(1, size // 12)
    cells = [a + 2 * pad for a in advances]
    width = sum(cells)
    args = ["convert", "-size", f"{width}x{height}", "xc:black", "-font", ttf, "-pointsize", str(size), "-fill", "white"]
    x = 0
    for ch, cell in zip(chars, cells):
        if ch != " ":
            args += ["-annotate", f"+{x + pad}+{ascent}", im_text(ch)]
        x += cell
    pixels = subprocess.run(args + ["-depth", "8", "gray:-"], capture_output=True, check=True).stdout
    assert len(pixels) == width * height

    # 16 coverage levels: runs of zeros -> 'A'..'Z' (run length 1..26), level v -> 'a'..'o' (1..15)
    out, run = [], 0
    for p in pixels:
        level = (p + 8) // 17
        if level == 0:
            run += 1
            if run == 26:
                out.append("Z"); run = 0
            continue
        if run:
            out.append(chr(ord("A") + run - 1)); run = 0
        out.append(chr(ord("a") + level - 1))
    if run:
        out.append(chr(ord("A") + run - 1))
    rle = "".join(out)

    lines = [f"/* {os.path.basename(ttf)} at {size} pt: {len(chars)} glyphs, {width}x{height} strip */"]
    glyph_rows, x = [], 0
    for ch, adv, cell in zip(chars, advances, cells):
        glyph_rows.append(f"    {{{adv}, {cell}, {x}}},")
        x += cell
    lines.append(f"static const AtlasGlyph {name}_glyphs[] = {{\n" + "\n".join(glyph_rows) + "\n};")
    chunks = [rle[i:i + 96] for i in range(0, len(rle), 96)]
    # one string per line keeps every literal far below the 4095 characters ISO C guarantees
    lines.append(f"static const char *const {name}_rle[] = {{\n" + "\n".join(f'    "{c}",' for c in chunks) + "\n    0\n};")
    lines.append(f'static const AtlasFont {name} = {{"{chars if name == "font_big" else ""}", {ord(chars[0])}, '
                 f"{len(chars)}, {width}, {height}, {ascent}, {pad}, {name}_glyphs, {name}_rle}};")
    return "\n".join(lines), len(rle)


def main():
    parts, total = [], 0
    for name, ttf, size, chars in FONTS:
        text, n = render(name, os.path.join(FONT_DIR, ttf), size, chars)
        parts.append(text)
        total += n
    header = f"""/*
 * Generated by Apps/DigitPad/Tools/make_font_atlas.py - do not edit.
 * Glyphs rendered from DejaVu Sans (Bitstream Vera license, public domain changes;
 * https://dejavu-fonts.github.io/License.html).
 */

#pragma once

typedef struct {{
    unsigned short advance;     /* pen advance in pixels */
    unsigned short width;       /* cell width in the strip (advance + 2 * pad) */
    unsigned short x;           /* cell offset in the strip */
}} AtlasGlyph;

typedef struct {{
    const char *chars;          /* explicit character list, or "" for a contiguous range */
    int first, count;           /* first character code (contiguous range) and glyph count */
    int width, height, ascent, pad;
    const AtlasGlyph *glyphs;
    /* strip pixels, row-major, as NULL-terminated string pieces:
       'A'..'Z' = 1..26 transparent pixels, 'a'..'o' = coverage 1..15 */
    const char *const *rle;
}} AtlasFont;

""" + "\n\n".join(parts) + "\n"
    with open(OUT, "w") as f:
        f.write(header)
    print(f"wrote {OUT}: {total} encoded pixels, {len(header)} bytes")


if __name__ == "__main__":
    main()
