# SPDX-License-Identifier: MIT
# Copyright (c) 2026 pka_human (pka_human@proton.me)
"""Keeps the library's ABI: what a program built against the newest release relies on.

    check_abi.py source OUT.c                    # a program printing the public structs' layouts,
                                                 # the enumerators' values and the integer constants
    check_abi.py check DUMP BASELINE [NM LIB]    # compare with Tests/Data/abi.txt (and, with nm, the
                                                 # library's exported symbols with Src/Spingalett.map)
    check_abi.py update DUMP BASELINE            # record the ABI of a release

The baseline holds every struct's size and fields (offset and size), every enumerator's value, the
integer constants and every function's declaration, as the newest release has them. A later 1.x may
add (fields in the reserved space, enumerators, functions); nothing it holds may change or go. Not
held: the reserved words themselves (fields added before them shrink them), the *_COUNT enumerators
and SPINGALETT_FORMAT_VERSION, which grow with the kinds of layers. Layouts are compared on 64-bit
platforms, where they are the same (the structs have no `long`); functions everywhere.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'docs'))
import make_reference  # noqa: E402  (the headers' parser)

MAP = os.path.join(ROOT, 'Src', 'Spingalett.map')
GROWING = re.compile(r'(_COUNT$|^SPINGALETT_FORMAT_VERSION$)')


def declarations():
    """(kind, name, declaration) of the public headers, the short names left out."""
    out = []
    for header, _ in make_reference.HEADERS:
        text = open(os.path.join(ROOT, 'Include', 'Spingalett', header)).read()
        text = text.split('#if defined(SPINGALETT_SHORT_NAMES)')[0]
        out += [(k, n, d) for k, n, d, _ in make_reference.items(text)]
    return out


def strip_comments(text):
    return re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)


def body(decl):
    text = strip_comments(decl)
    return text[text.index('{') + 1:text.rindex('}')]


def struct_fields(decl):
    """The field names of a `typedef struct { ... } Name;`, in order."""
    names = []
    for member in body(decl).split(';'):
        member = member.strip()
        if not member:
            continue
        for declarator in member.split(','):
            declarator = re.sub(r'\[[^\]]*\]', '', declarator).strip()
            names.append(re.findall(r'\w+', declarator)[-1])
    return names


def enumerators(decl):
    return [re.match(r'\s*(\w+)', e).group(1) for e in body(decl).split(',') if e.strip()]


def functions():
    """name -> declaration, whitespace normalized."""
    out = {}
    for kind, name, decl in declarations():
        if kind == 'function':
            decl = re.sub(r'\s+', ' ', decl).replace('( ', '(').replace(' )', ')')
            out[name] = decl
    return out


def write_source(path):
    lines = ['/* Generated by Tests/check_abi.py from the public headers. */',
             '#include <Spingalett/Spingalett.h>', '#include <stddef.h>', '#include <stdio.h>', '',
             '#define SIZE(T) printf("struct %s size %zu\\n", #T, sizeof(T))',
             '#define FIELD(T, f) printf("field %s.%s offset %zu size %zu\\n", #T, #f, offsetof(T, f), '
             'sizeof(((T *)0)->f))',
             '#define VALUE(kind, v) printf("%s %s %lld\\n", kind, #v, (long long)(v))', '',
             'int main(void) {', '    printf("pointer %zu\\n", sizeof(void *));']
    for kind, name, decl in declarations():
        if kind == 'type' and re.match(r'typedef struct\s*\{', decl):
            lines.append('    SIZE(%s);' % name)
            lines += ['    FIELD(%s, %s);' % (name, f) for f in struct_fields(decl)]
        elif kind == 'type' and re.match(r'typedef enum\s*\{', decl):
            lines += ['    VALUE("enum", %s);' % e for e in enumerators(decl)]
        elif kind == 'constant':
            value = decl.split(None, 2)[2]
            if not value.startswith('"'):
                lines.append('    VALUE("constant", %s);' % name)
    lines += ['    return 0;', '}', '']
    open(path, 'w').write('\n'.join(lines))


def current(dump):
    """key -> value of what the headers and the compiled dump give now."""
    out = {}
    for line in subprocess.run([dump], check=True, capture_output=True, text=True).stdout.splitlines():
        words = line.split()
        if words[0] == 'pointer':
            out['pointer'] = words[1]
        else:
            out[words[0] + ' ' + words[1]] = ' '.join(words[2:])
    for name, decl in functions().items():
        out['function ' + name] = decl
    return out


def held(key):
    """Whether a later release must keep this entry as it is."""
    name = key.split(' ', 1)[1] if ' ' in key else key
    return not (key.startswith('field ') and name.endswith('.reserved')) and not GROWING.search(name)


def read_baseline(path):
    out = {}
    for line in open(path):
        line = line.rstrip('\n')
        if line and not line.startswith('#'):
            kind, name, value = line.split(' ', 2)
            out[kind + ' ' + name] = value
    return out


def map_symbols():
    text = strip_comments(open(MAP).read())
    return set(re.findall(r'\b(spingalett_\w+);', text))


def check(dump, baseline, nm=None, library=None):
    errors = []
    now, before = current(dump), read_baseline(baseline)
    layouts = now.get('pointer') == '8'
    if not layouts:
        print('check_abi: %s-byte pointers, layouts not compared' % now.get('pointer'))
    for key, value in before.items():
        if not layouts and not key.startswith('function '):
            continue
        if key not in now:
            errors.append('removed: %s %s' % (key, value))
        elif now[key] != value:
            errors.append('changed: %s\n    was %s\n    now %s' % (key, value, now[key]))
    added = [k for k in now if k not in before and k != 'pointer' and held(k)]

    # the version script lists the headers' functions, and the library exports them (ELF)
    declared, mapped = set(functions()), map_symbols()
    for name in sorted(declared - mapped):
        errors.append('declared but not in Src/Spingalett.map: %s' % name)
    for name in sorted(mapped - declared):
        errors.append('in Src/Spingalett.map but not declared: %s' % name)
    if nm and library:
        out = subprocess.run([nm, '-D', '--defined-only', library], check=True, capture_output=True,
                             text=True).stdout
        exported = {}
        for line in out.splitlines():
            symbol = line.split()[-1]
            if symbol.startswith('spingalett_'):
                name, _, version = symbol.partition('@@')
                exported[name] = version
        for name in sorted(mapped - set(exported)):
            errors.append('not exported by the library: %s' % name)
        for name in sorted(set(exported) - mapped):
            errors.append('exported but not in Src/Spingalett.map: %s' % name)
        # (nm before binutils 2.35 does not print versions)
        if any(exported.values()):
            for name, version in sorted(exported.items()):
                if not version:
                    errors.append('exported without a symbol version: %s' % name)

    for e in errors:
        print(e)
    print('check_abi: %d entries of the baseline, %d added since, %d errors' % (len(before), len(added),
                                                                                len(errors)))
    return 1 if errors else 0


def update(dump, baseline):
    now = current(dump)
    if now.get('pointer') != '8':
        sys.exit('check_abi: the baseline is recorded on a 64-bit platform')
    version = open(os.path.join(ROOT, 'CMakeLists.txt')).read()
    version = re.search(r'project\(Spingalett VERSION ([\d.]+)', version).group(1)
    lines = ['# The ABI of Spingalett %s, written by Tests/check_abi.py update: later releases keep every' % version,
             '# entry (layouts on 64-bit platforms). Recorded again at each release, with what it added.']
    lines += ['%s %s' % (k, v) for k, v in now.items() if k != 'pointer' and held(k)]
    open(baseline, 'w').write('\n'.join(lines) + '\n')
    print('check_abi: wrote %s (%d entries)' % (baseline, len(lines) - 2))


if __name__ == '__main__':
    args = sys.argv[1:]
    if len(args) == 2 and args[0] == 'source':
        write_source(args[1])
    elif len(args) in (3, 5) and args[0] == 'check':
        sys.exit(check(*args[1:]))
    elif len(args) == 3 and args[0] == 'update':
        update(args[1], args[2])
    else:
        sys.exit(__doc__)
