# SPDX-License-Identifier: MIT
# Copyright (c) 2026 pka_human (pka_human@proton.me)
"""Writes docs/Reference.md from the public headers: every declaration (function, builder macro,
type, constant) with the comment before it, in the headers' order.

    python docs/make_reference.py            # rewrite docs/Reference.md
    python docs/make_reference.py --check    # exit 1 when it differs from what the headers give
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADERS = [
    ('Spingalett.h', 'The library: networks, training, inference, files, data sets, the GPU'),
    ('Spingalett.Inference.h', 'The inference engine: models over .slett images, without heap or I/O'),
]
OUT = os.path.join(ROOT, 'docs', 'Reference.md')


def clean_comment(text):
    """The text of a block comment, its leading stars and indentation removed."""
    body = text[2:-2]
    lines = [re.sub(r'^\s*\* ?', '', l) if l.lstrip().startswith('*') else l.strip() for l in body.split('\n')]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    paragraphs, current = [], []
    for l in lines:
        if l.strip():
            current.append(l.strip())
        elif current:
            paragraphs.append(' '.join(current))
            current = []
    if current:
        paragraphs.append(' '.join(current))
    return '\n\n'.join(paragraphs)


def items(text):
    """(kind, name, declaration, comment) for every public declaration, in order."""
    out, comment, i = [], None, 0
    lines = text.split('\n')
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if stripped.startswith('/*') and not stripped.startswith('/**/'):
            j = i
            while '*/' not in lines[j]:
                j += 1
            block = '\n'.join(lines[i:j + 1])
            # a comment followed by a blank line describes a section, not the next declaration
            following = lines[j + 1].strip() if j + 1 < len(lines) else ''
            comment = clean_comment(block[block.index('/*'):block.rindex('*/') + 2])
            if comment.startswith('SPDX'):
                comment = None
            elif not following or (following.startswith('#') and not following.startswith('#define')):
                out.append(('section', '', '', comment))
                comment = None
            i = j + 1
            continue
        if stripped.startswith('SPINGALETT_API'):
            j = i
            while ';' not in lines[j]:
                j += 1
            decl = ' '.join(l.strip() for l in lines[i:j + 1]).replace('SPINGALETT_API ', '')
            name = re.search(r'(\w+)\s*\(', decl).group(1)
            out.append(('function', name, decl, comment))
            comment, i = None, j + 1
            continue
        m = re.match(r'#define (spingalett_\w+)\(\.\.\.\)\s+(.*)', stripped)
        if m:
            out.append(('builder', m.group(1), stripped, comment))
            comment, i = None, i + 1
            continue
        m = re.match(r'#define (SPINGALETT_\w+)\s+(.+)', stripped)
        if m and not m.group(1).startswith('SPINGALETT_API'):
            out.append(('constant', m.group(1), stripped, comment))
            comment, i = None, i + 1
            continue
        if stripped.startswith('typedef'):
            j = i
            if '{' in stripped:
                depth = 0
                while True:
                    depth += lines[j].count('{') - lines[j].count('}')
                    if depth == 0 and ';' in lines[j]:
                        break
                    j += 1
            else:
                while ';' not in lines[j]:
                    j += 1
            decl = '\n'.join(lines[i:j + 1])
            name = re.search(r'(\w+)\s*;\s*$', lines[j]) or re.search(r'\(\*(\w+)\)', decl)
            out.append(('type', name.group(1), decl, comment))
            comment, i = None, j + 1
            continue
        if stripped and not stripped.startswith('#') and not stripped.startswith('extern') and stripped != '}':
            comment = None
        i += 1
    return out


def render():
    md = ['# API reference', '',
          'Every public declaration of `Include/Spingalett/` with its comment, in the order of the headers',
          '(generated by `docs/make_reference.py` from them; edit the headers, not this file). The names',
          'without the prefix of 0.x are in `Spingalett.Short.h`; the C++ interface is `Spingalett.hpp`.', '']
    parsed = []
    for header, title in HEADERS:
        text = open(os.path.join(ROOT, 'Include', 'Spingalett', header)).read()
        text = text.split('#if defined(SPINGALETT_SHORT_NAMES)')[0]     # the short names: not listed
        parsed.append((header, title, items(text)))
    # an index of the names, each linking to its entry (GitHub's anchors: the heading's text, lower case,
    # without the punctuation)
    for header, title, entries in parsed:
        names = [n + ('()' if k in ('function', 'builder') else '') for k, n, _, _ in entries if k != 'section']
        links = ['[`%s`](#%s)' % (n, re.sub(r'[^a-z0-9_-]', '', n.lower())) for n in names]
        md += ['**%s:** ' % header + ', '.join(links), '']
    for header, title, entries in parsed:
        md += ['## ' + header, '', title + '.', '']
        for kind, name, decl, comment in entries:
            if kind == 'section':
                if comment and not comment.startswith('SPDX'):
                    md += [comment, '']
                continue
            md += ['### `' + name + ('()' if kind in ('function', 'builder') else '') + '`', '']
            if comment:
                md += [comment, '']
            md += ['```c', decl, '```', '']
    return '\n'.join(md).rstrip('\n') + '\n'


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv:
        current = open(OUT).read() if os.path.exists(OUT) else ''
        if current != text:
            print('docs/Reference.md is out of date: run python docs/make_reference.py')
            sys.exit(1)
        print('docs/Reference.md is up to date')
    else:
        open(OUT, 'w').write(text)
        print('wrote', os.path.relpath(OUT, ROOT))
