# cmake -DNM=<nm> -DLIBRARY=<engine library> -P CheckEngineSymbols.cmake
# Fails when the inference engine refers to the heap, stdio, files, OpenMP or threads.
execute_process(COMMAND ${NM} -u ${LIBRARY} OUTPUT_VARIABLE undefined RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${NM} -u ${LIBRARY} failed")
endif()
string(REPLACE "\n" ";" lines "${undefined}")
set(symbols "")
foreach(line IN LISTS lines)
    string(REGEX REPLACE "^.*[ \t]U[ \t]+" "" sym "${line}")
    string(STRIP "${sym}" sym)
    string(REGEX REPLACE "^_+" "" sym "${sym}")         # Mach-O prefixes C names with _
    if(sym STREQUAL "" OR sym MATCHES ":$")
        continue()
    endif()
    list(APPEND symbols ${sym})
endforeach()
list(REMOVE_DUPLICATES symbols)
set(bad "")
foreach(sym IN LISTS symbols)
    if(sym MATCHES "^(malloc|calloc|realloc|free|aligned_alloc|posix_memalign|printf|fprintf|sprintf|snprintf|puts|fputs|fopen|fclose|fread|fwrite|fseek|ftell|exit|abort)$"
       OR sym MATCHES "^(omp_|GOMP_|pthread_|emutls)")
        list(APPEND bad ${sym})
    endif()
endforeach()
message(STATUS "The inference engine uses: ${symbols}")
if(bad)
    message(FATAL_ERROR "The inference engine must not use: ${bad}")
endif()
