# SPDX-License-Identifier: MIT
# Copyright (c) 2026 pka_human (pka_human@proton.me)
#
# The CUDA backend (Src/Gpu/Spingalett.Cuda.c): the kernels of Src/Gpu/Cuda compiled to PTX by clang
# (CUDA as a language, without the CUDA toolkit: -nocudainc -nocudalib), one unit of Kernels.def a
# module, and embedded. The CUDA driver (libcuda, nvcuda.dll) is opened at run time and compiles the PTX
# for the GPU it finds, so building needs only a clang with the NVPTX target, and the library loads and
# runs without CUDA. PTX is the same on every platform: SPINGALETT_PTX_DIR takes the units of another
# build (its Cuda/<unit>.ptx.inc files) where there is no such clang.

set(SPINGALETT_CUDA AUTO CACHE STRING "CUDA backend: AUTO (when a clang that targets NVPTX is found), ON or OFF")
set_property(CACHE SPINGALETT_CUDA PROPERTY STRINGS AUTO ON OFF)
set(SPINGALETT_PTX_DIR "" CACHE PATH "Compiled PTX units (<unit>.ptx.inc) to use instead of clang")
set(SPINGALETT_HAS_CUDA OFF)

# the PTX: Ampere (sm_80) and later, in the ISA of CUDA 11.0 (drivers of 2020 on)
set(SPINGALETT_CUDA_FLAGS -x cuda --cuda-device-only --cuda-gpu-arch=sm_80 -nocudainc -nocudalib -O3
    -ffp-contract=off -std=c++17 -Xclang -target-feature -Xclang +ptx70)

if(NOT SPINGALETT_CUDA STREQUAL "OFF" AND NOT SPINGALETT_PTX_DIR)
    if(NOT SPINGALETT_CUDA_CLANG)
        if(CMAKE_C_COMPILER_ID STREQUAL "Clang")
            set(candidates ${CMAKE_C_COMPILER})
        endif()
        find_program(found_clang NAMES clang clang-22 clang-21 clang-20 clang-19 clang-18)
        list(APPEND candidates ${found_clang})
        unset(found_clang CACHE)
        # the first that compiles a kernel to PTX
        set(probe ${CMAKE_CURRENT_BINARY_DIR}/cuda_probe.cu)
        file(WRITE ${probe} "extern \"C\" __attribute__((global)) void k(float *x) { x[0] = 1.0f; }\n")
        foreach(candidate ${candidates})
            execute_process(COMMAND ${candidate} ${SPINGALETT_CUDA_FLAGS} -S -o ${probe}.ptx ${probe}
                            RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET)
            if(rc EQUAL 0)
                set(SPINGALETT_CUDA_CLANG ${candidate} CACHE FILEPATH "clang that compiles the CUDA kernels to PTX")
                break()
            endif()
        endforeach()
    endif()
endif()

if(NOT SPINGALETT_CUDA STREQUAL "OFF")
    if(SPINGALETT_CUDA_CLANG OR SPINGALETT_PTX_DIR)
        set(SPINGALETT_HAS_CUDA ON)
    elseif(SPINGALETT_CUDA STREQUAL "ON")
        message(FATAL_ERROR "SPINGALETT_CUDA=ON needs a clang with the NVPTX target (SPINGALETT_CUDA_CLANG) or SPINGALETT_PTX_DIR")
    else()
        message(STATUS "Spingalett: CUDA backend off (no clang with the NVPTX target)")
    endif()
endif()

if(SPINGALETT_HAS_CUDA)
    set(cuda_dir ${CMAKE_CURRENT_SOURCE_DIR}/Src/Gpu/Cuda)
    set(out_dir ${CMAKE_CURRENT_BINARY_DIR}/Cuda)
    file(MAKE_DIRECTORY ${out_dir})
    file(STRINGS ${cuda_dir}/Kernels.def unit_lines REGEX "^SPG_CUDA_UNIT\\(")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${cuda_dir}/Kernels.def)
    file(GLOB cuda_headers ${cuda_dir}/*.cuh)
    set(ptx_files)
    set(header "/* Generated by cmake/Cuda.cmake from Src/Gpu/Cuda/Kernels.def */\n\n")
    set(table "static const struct { const char *name; const char *ptx; } spg_cuda_units[] = {\n")
    foreach(line ${unit_lines})
        string(REGEX REPLACE "^SPG_CUDA_UNIT\\(([A-Za-z0-9_]+), *([A-Za-z0-9_]+), *\"([^\"]*)\"\\).*" "\\1;\\2;\\3" parts "${line}")
        list(GET parts 0 unit)
        list(GET parts 1 source)
        list(GET parts 2 defines)
        separate_arguments(defines)
        set(out ${out_dir}/${unit}.ptx.inc)
        if(SPINGALETT_PTX_DIR)
            configure_file(${SPINGALETT_PTX_DIR}/${unit}.ptx.inc ${out} COPYONLY)
        else()
            add_custom_command(OUTPUT ${out}
                COMMAND ${SPINGALETT_CUDA_CLANG} ${SPINGALETT_CUDA_FLAGS} -DSPG_ENTRY=spg_${unit} ${defines}
                        -S -o ${out_dir}/${unit}.ptx ${cuda_dir}/${source}.cu
                COMMAND ${CMAKE_COMMAND} -DIN=${out_dir}/${unit}.ptx -DOUT=${out} -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/PtxToC.cmake
                DEPENDS ${cuda_dir}/${source}.cu ${cuda_headers} ${CMAKE_CURRENT_SOURCE_DIR}/Src/Gpu/Spingalett.GpuPush.h
                        ${CMAKE_CURRENT_SOURCE_DIR}/cmake/PtxToC.cmake
                COMMENT "Compiling CUDA kernel ${unit} (${source}.cu)"
                VERBATIM)
        endif()
        list(APPEND ptx_files ${out})
        string(APPEND header "static const char spg_ptx_${unit}[] =\n#include \"${unit}.ptx.inc\"\n;\n")
        string(APPEND table "    {\"${unit}\", spg_ptx_${unit}},\n")
    endforeach()
    string(APPEND header "\n${table}};\n")
    file(CONFIGURE OUTPUT ${out_dir}/Spingalett.CudaKernels.h CONTENT "${header}" @ONLY)
    add_custom_target(spingalett_cuda_kernels DEPENDS ${ptx_files})
    if(SPINGALETT_PTX_DIR)
        message(STATUS "Spingalett: CUDA backend on (PTX from ${SPINGALETT_PTX_DIR})")
    else()
        message(STATUS "Spingalett: CUDA backend on (${SPINGALETT_CUDA_CLANG})")
    endif()
endif()
