# SPDX-License-Identifier: MIT
# Copyright (c) 2026 pka_human (pka_human@proton.me)
#
# The Vulkan compute backend (Src/Gpu): the shaders of Spingalett.Kernels.def compiled to SPIR-V
# with glslc and embedded in the library. Vulkan itself is opened at run time, so building it
# needs only the headers and glslc, and the library loads and runs on the CPU without Vulkan.
# SPIR-V is the same on every platform: SPINGALETT_SPIRV_DIR takes the compiled shaders of another
# build (its Gpu/<kernel>.spv.inc files) where there is no glslc.

set(SPINGALETT_VULKAN AUTO CACHE STRING "Vulkan compute backend: AUTO (when glslc and the Vulkan headers are found), ON or OFF")
set_property(CACHE SPINGALETT_VULKAN PROPERTY STRINGS AUTO ON OFF)
set(SPINGALETT_SPIRV_DIR "" CACHE PATH "Compiled shaders (<kernel>.spv.inc) to use instead of glslc")
set(SPINGALETT_HAS_VULKAN OFF)

if(NOT SPINGALETT_VULKAN STREQUAL "OFF")
    if(NOT SPINGALETT_SPIRV_DIR)
        find_program(SPINGALETT_GLSLC glslc HINTS $ENV{VULKAN_SDK}/bin)
    endif()
    find_path(SPINGALETT_VULKAN_INCLUDE vulkan/vulkan_core.h HINTS $ENV{VULKAN_SDK}/include)
    if((SPINGALETT_GLSLC OR SPINGALETT_SPIRV_DIR) AND SPINGALETT_VULKAN_INCLUDE)
        set(SPINGALETT_HAS_VULKAN ON)
    elseif(SPINGALETT_VULKAN STREQUAL "ON")
        message(FATAL_ERROR "SPINGALETT_VULKAN=ON needs glslc (shaderc) or SPINGALETT_SPIRV_DIR, and the Vulkan headers")
    else()
        message(STATUS "Spingalett: Vulkan backend off (glslc or the Vulkan headers not found)")
    endif()
endif()

if(SPINGALETT_HAS_VULKAN)
    set(gpu_dir ${CMAKE_CURRENT_SOURCE_DIR}/Src/Gpu)
    set(out_dir ${CMAKE_CURRENT_BINARY_DIR}/Gpu)
    file(MAKE_DIRECTORY ${out_dir})
    file(STRINGS ${gpu_dir}/Spingalett.Kernels.def kernel_lines REGEX "^SPG_KERNEL\\(")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${gpu_dir}/Spingalett.Kernels.def)

    set(spirv_files)
    set(header "/* Generated by cmake/Vulkan.cmake from Src/Gpu/Spingalett.Kernels.def */\n\n#include <stddef.h>\n#include <stdint.h>\n\n")
    set(table "static const uint32_t *const spg_kernel_spirv[] = {\n")
    set(sizes "static const size_t spg_kernel_spirv_size[] = {\n")
    set(names "static const char *const spg_kernel_names[] = {\n")
    foreach(line ${kernel_lines})
        string(REGEX REPLACE "^SPG_KERNEL\\(([A-Za-z0-9_]+)\\).*" "\\1" kernel "${line}")
        set(src ${gpu_dir}/Shaders/${kernel}.comp)
        set(out ${out_dir}/${kernel}.spv.inc)
        if(SPINGALETT_SPIRV_DIR)
            add_custom_command(OUTPUT ${out}
                COMMAND ${CMAKE_COMMAND} -E copy ${SPINGALETT_SPIRV_DIR}/${kernel}.spv.inc ${out}
                DEPENDS ${SPINGALETT_SPIRV_DIR}/${kernel}.spv.inc
                COMMENT "Taking shader ${kernel} from ${SPINGALETT_SPIRV_DIR}"
                VERBATIM)
        else()
            add_custom_command(OUTPUT ${out}
                COMMAND ${SPINGALETT_GLSLC} --target-env=vulkan1.2 -O -mfmt=c -MD -MF ${out}.d -o ${out} ${src}
                DEPENDS ${src}
                DEPFILE ${out}.d
                COMMENT "Compiling shader ${kernel}.comp"
                VERBATIM)
        endif()
        list(APPEND spirv_files ${out})
        string(APPEND header "static const uint32_t spg_spirv_${kernel}[] =\n#include \"${kernel}.spv.inc\"\n;\n")
        string(APPEND table "    spg_spirv_${kernel},\n")
        string(APPEND sizes "    sizeof spg_spirv_${kernel},\n")
        string(APPEND names "    \"${kernel}\",\n")
    endforeach()
    string(APPEND header "\n${table}};\n${sizes}};\n${names}};\n")
    file(CONFIGURE OUTPUT ${out_dir}/Spingalett.Kernels.h CONTENT "${header}" @ONLY)

    add_custom_target(spingalett_shaders DEPENDS ${spirv_files})
    add_dependencies(spingalett spingalett_shaders)
    target_sources(spingalett PRIVATE ${gpu_dir}/Spingalett.Vulkan.c ${gpu_dir}/Spingalett.GpuKernels.c
                                      ${gpu_dir}/Spingalett.Gpu.c)
    set_source_files_properties(${gpu_dir}/Spingalett.Vulkan.c PROPERTIES OBJECT_DEPENDS "${spirv_files}")
    target_include_directories(spingalett PRIVATE ${gpu_dir} ${out_dir} ${SPINGALETT_VULKAN_INCLUDE})
    if(NOT WIN32)
        target_link_libraries(spingalett PRIVATE ${CMAKE_DL_LIBS})
    endif()
    if(SPINGALETT_SPIRV_DIR)
        message(STATUS "Spingalett: Vulkan backend on (shaders from ${SPINGALETT_SPIRV_DIR})")
    else()
        message(STATUS "Spingalett: Vulkan backend on (${SPINGALETT_GLSLC})")
    endif()
endif()
